/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 20 19:17:04 GMT 2026
 */

package com.demo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.demo.Calculator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Calculator_ESTest extends Calculator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.clamp(1, 1, 2623);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      boolean boolean0 = calculator0.isEven((-611));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.max((-1987), (-1987));
      assertEquals((-1987), int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.absolute(1726);
      assertEquals(1726, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      double double0 = calculator0.divide(1, 122.0);
      assertEquals(0.00819672131147541, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.subtract(199, (-1));
      assertEquals(200, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.subtract(0, 1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.multiply(1, 1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.multiply(1702, (-1399));
      assertEquals((-2381098), int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.max((-437), 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.max((-32), (-1852));
      assertEquals((-32), int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      long long0 = calculator0.factorial(563);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      long long0 = calculator0.factorial(22);
      assertEquals((-1250660718674968576L), long0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      double double0 = calculator0.divide(0, (-966.8));
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      double double0 = calculator0.divide(6L, (-1852));
      assertEquals((-0.0032397408207343412), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.clamp(1, 1, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.add(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.add((-1), 0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      // Undeclared exception!
      calculator0.isPrime(2140179281);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      // Undeclared exception!
      calculator0.factorial(1073741824);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.clamp(2, (-14), (-14));
      assertEquals((-14), int0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.clamp((-1), 3, 0);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.clamp((-1), (-2264), (-1));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      boolean boolean0 = calculator0.isPrime(3773);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      boolean boolean0 = calculator0.isPrime(3);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      boolean boolean0 = calculator0.isPrime(9);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      boolean boolean0 = calculator0.isPrime(2);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      boolean boolean0 = calculator0.isPrime((-1711));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      boolean boolean0 = calculator0.isPrime(3426);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      long long0 = calculator0.factorial(3);
      assertEquals(6L, long0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      long long0 = calculator0.factorial(0);
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      // Undeclared exception!
      try { 
        calculator0.factorial((-437));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Factorial not defined for negative numbers
         //
         verifyException("com.demo.Calculator", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      long long0 = calculator0.factorial(1);
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      boolean boolean0 = calculator0.isEven((-1852));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      boolean boolean0 = calculator0.isEven(1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.max(4040, 0);
      assertEquals(4040, int0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.absolute((-12));
      assertEquals(12, int0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.absolute(0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      // Undeclared exception!
      try { 
        calculator0.divide(0, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot divide by zero
         //
         verifyException("com.demo.Calculator", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.add(1713, 1713);
      assertEquals(3426, int0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.subtract(3, 3);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.multiply(0, (-646));
      assertEquals(0, int0);
  }
}
