/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 20 19:18:08 GMT 2026
 */

package com.demo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.demo.StringUtils;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class StringUtils_ESTest extends StringUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      String string0 = stringUtils0.truncate("", 0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      String string0 = stringUtils0.reverse("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      boolean boolean0 = stringUtils0.isPalindrome("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      // Undeclared exception!
      try { 
        stringUtils0.truncate("x,u TdwT", (-1));
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      String string0 = stringUtils0.truncate("", 1);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      String string0 = stringUtils0.truncate((String) null, 0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      String string0 = stringUtils0.truncate("|}'-b[1Iadut*?", 0);
      assertEquals("...", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      boolean boolean0 = stringUtils0.isNumeric("4");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      boolean boolean0 = stringUtils0.isNumeric("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      boolean boolean0 = stringUtils0.isNumeric("Tbp~ rj5");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      boolean boolean0 = stringUtils0.isNumeric((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      String string0 = stringUtils0.titleCase("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      String string0 = stringUtils0.titleCase(" !CXiQc?$En\u0000bIj~");
      assertEquals("!cxiqc?$en\u0000bij~", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      String string0 = stringUtils0.titleCase((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      boolean boolean0 = stringUtils0.isPalindrome((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      boolean boolean0 = stringUtils0.isPalindrome("0;vqt:u#o.hH");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      int int0 = stringUtils0.countChar("aDH:d4cLwiIn?fg.0r", '');
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      int int0 = stringUtils0.countChar((String) null, 'v');
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      int int0 = stringUtils0.countChar("|}'-b[1Iadut*?", 'H');
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      // Undeclared exception!
      try { 
        stringUtils0.reverse((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Input cannot be null
         //
         verifyException("com.demo.StringUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      StringUtils stringUtils0 = new StringUtils();
      String string0 = stringUtils0.reverse("Lk/K.uG]");
      assertEquals("]Gu.K/kL", string0);
  }
}
