# Define the default driver
webdriver.driver=firefox
webdriver.autodownload=true
headless.mode=false

# Appears at the top of the reports
serenity.project.name=Lab5

# Root package for JUnit acceptance tests
serenity.test.root=org.example.features
