# Define the default driver
webdriver.driver = chrome
webdriver.autodownload = true
headless.mode = true

# Appears at the top of the reports
serenity.project.name=Lab5

# Root package for JUnit acceptance tests
serenity.test.root=org.example.features


webdriver.chrome.driver = /usr/bin/chromedriver
chrome.switches = --start-maximized;--disable-notifications;--remote-allow-origins=*